### ISSUE TITLE
Making the theme of the website even

### ISSUE THREAD

**Issue by goyalmuskan** [smaranjitghose/girlscript_app#101]
The website currently doesn't follow one particular theme. May I work on this issue? @smaranjitghose

**Comment by manan-bedi2908** [comment]
@goyalmuskan I am working on it as the issue was opened to improve the home page and other pages!

**Comment by manan-bedi2908** [comment]
You can ask @smaranjitghose if we could work together as we have to change the theme of all pages

**Comment by goyalmuskan** [comment]
Yes, Sure @manan-bedi2908 . May I too contribute to changing the theme of the website? @smaranjitghose

**Comment by ousnik** [comment]
Go ahead. Both. Coordinate with each other as rqrd.

**Comment by goyalmuskan** [comment]
Sure @ousnik !!

**Comment by sukkritsharmaofficial** [comment]
Further work needs to be done to the website for uniformity.

**Comment by Yashank18** [comment]
I have some ideas for it, I can work with @goyalmuskan on it.

**Comment by goyalmuskan** [comment]
Sure @Yashank18! If @smaranjitghose or @sukkritsharmaofficial can assign you too?

**Comment by sukkritsharmaofficial** [comment]
@goyalmuskan and @Yashank18 Please go ahead with it 👍
