### ISSUE TITLE
Right overflow issues in teams.dart

### ISSUE THREAD

**Issue by puneethkanna** [smaranjitghose/girlscript_app#108]
**Note:** For getting an element in center, use column row or Center(). Don't use padding because it changes from screen size.

**Comment by kamal-kaur04** [comment]
Hello @smaranjitghose @puneethkanna Can I take this issue?

**Comment by kamal-kaur04** [comment]
@smaranjitghose @ousnik I am getting this error while building the project. 
`Gradle does not have execution permission.
    You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
Gradle task assembleDebug failed with exit code 1`

how to access the project?

**Comment by kamal-kaur04** [comment]
I just ran `flutter clean` will it effect the project?
