### ISSUE TITLE
Improvement of the homepage

### ISSUE THREAD

**Issue by Sapna2001** [smaranjitghose/girlscript_app#114]
![Screenshot (24)](https://user-images.githubusercontent.com/56690856/76168161-ed258500-6192-11ea-98c7-59557c07e7b6.png)

The top bar seems congested with social media icons and the top bar. So I would like to give proper spacing to improve it.

**Comment by Sapna2001** [comment]
@smaranjitghose @ousnik I would like to work on this. Please assign me this issue.

**Comment by smaranjitghose** [comment]
I have already assigned an issue on this..Please see the most recent update and comment there for this
