### ISSUE TITLE
Improve home screen of the application

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#135]
I would like to improve the home screen widget as one shown in the README.md file and add further more enhancements.

**Comment by anushbhatia** [comment]
![Screenshot_20200313_204714_com android chrome](https://user-images.githubusercontent.com/40017559/76634156-e7051f00-656b-11ea-9402-7d9c2b0d13d0.jpg)

U can add something kind of this as beginning
