### ISSUE TITLE
Improve the ReadMe of the project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#136]
# Suggested Structure:

- Project Name
- Project Description
- Snapshots
- Tech Stack Used
- How to Contribute
- Learning Resources
- Code of Conduct
- Project Admins and Teams
- License

__Try to put in more emojis,gif,images__

# Some Resources to get started with:

- __Basics of GitHub Markdown__
https://guides.github.com/features/mastering-markdown/

- __Some more tips on GitHub Markdown__
https://ghost.org/changelog/markdown/

- __For creating badges__:
https://shields.io/

- __Quick Fetch badges__:
https://github.com/Naereen/badges

- __Emoji Cheatsheet__:
https://www.webfx.com/tools/emoji-cheat-sheet/

# Samples of the ReadMes of my other projects:

- https://github.com/smaranjitghose/PyDeceive
- https://github.com/smaranjitghose/DeepPixel

**Comment by hitha2000** [comment]
@smaranjitghose  please assign me this issue

**Comment by anushbhatia** [comment]
![1585418124194](https://user-images.githubusercontent.com/40017559/77830023-9e448d00-714b-11ea-9e8a-218e684887ff.png)
Solve this issue make custom icons and update them

**Comment by bharat-1809** [comment]
@anushbhatia 
I would like to work on this issue

**Comment by bharat-1809** [comment]
Is this correct ?
![jhgj](https://user-images.githubusercontent.com/58745044/77852989-26379f00-71ff-11ea-9997-912cefd27256.png)

**Comment by anushbhatia** [comment]
Try making it more colourful and if u can add custom icons that would be great

**Comment by bharat-1809** [comment]
> Try making it more colourful and if u can add custom icons that would be great

Ok I'll work on it.

**Comment by anushbhatia** [comment]
Status?

**Comment by bharat-1809** [comment]
Sorry for the delay, Just made a pull request please have a look

**Comment by anushbhatia** [comment]
![1586255612216](https://user-images.githubusercontent.com/40017559/78659662-86a69a80-78e9-11ea-9c8f-8b3ce2bf3c5e.png)
Resolve this issue

**Comment by himanshusharma89** [comment]
It works fine:
![image](https://user-images.githubusercontent.com/44980497/78661595-abe8d800-78ec-11ea-868b-a0c2a234babe.png)
