### ISSUE TITLE
A static website for this open source project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#137]
# Create a static website for describing this open-source project 

- __use the  docs folder of this repo (This is because we shall be setting up the GitHub  Pages from it)__
- Firstly give a PR to delete the existing contents of the __docs__ folder
- Use the current ReadMe as a starting point to build on

###  Suggested Structure:

- Project Title
- Project Description
- Snapshots
- Tech Stack Used
- How to Contribute
- Learning Resources
- Code of Conduct
- Animation to count number of contributors,pull-requests,issues
- Project Admins and Mentors ( Try to have a section or Card, with Name,description,social media links)
- License

### Currently hosting at:
smaranjitghose.github.io/girlscript_app

### Resources:
https://help.github.com/en/github/working-with-github-pages/about-github-pages

## Please do not use templates available on websites like HTML5UP,etc for this

**Comment by RaghavAwasthi** [comment]
I would like to work on this one. Can you assign me
