### ISSUE TITLE
Adding a notification button to home screen

### ISSUE THREAD

**Issue by swat1998** [smaranjitghose/girlscript_app#14]
To make a notification button on the  top right corner of the app home screen on the app bar. This button when clicked should redirect to a page with different notification in the list view. (make a empty function for the page.)

**Comment by infiniteoverflow** [comment]
I would like to work on this

**Comment by infiniteoverflow** [comment]
Should it be placed alongside the drawer icon??

**Comment by infiniteoverflow** [comment]
@swat1998 I have added this feature

**Comment by puneethkanna** [comment]
This issue is still open, even though it is merged.
