### ISSUE TITLE
Team Page 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#142]

**Comment by Anushka-shukla** [comment]
Sir , Assign me this issue

**Comment by shreyakapoor08** [comment]
can I work on this issue ?

**Comment by shreyakapoor08** [comment]
@anushbhatia can you please explain what exactly has to be done?

**Comment by anushbhatia** [comment]
Follow the current mockup and implement the design

**Comment by bharat-1809** [comment]
Can I work on it?

**Comment by shreyakapoor08** [comment]
@anushbhatia Hey, I just talked to bharat and got to know that the UI is based on flutter dart. But i have no prior experience on the same . So I am unassigning myself from this issue. Sorry for the confusion from my end.
