### ISSUE TITLE
Add more fonts for the app to be used

### ISSUE THREAD

**Issue by swat1998** [smaranjitghose/girlscript_app#15]
Add more fonts and declare it in the pubspec.yaml file.

**Comment by annu12340** [comment]
I would like to work on this

**Comment by smaranjitghose** [comment]
Go ahead

**Comment by siddhishree** [comment]
It has been 5 days since the issue is assigned. Can I take this issue now, if there hasn't been any progress yet? @smaranjitghose

**Comment by annu12340** [comment]
Yes siddhishree, you may take it up. (due to personal reasons, I would be able to work on it)

**Comment by annu12340** [comment]
Yes siddhishree, you may take it up. (due to personal reasons, I would be able to work on it)
