### ISSUE TITLE
Projects page is empty 

### ISSUE THREAD

**Issue by swat1998** [smaranjitghose/girlscript_app#16]
Add scrollable cards to the page with 3 icons (arbitrary icons can be used for now).

**Comment by infiniteoverflow** [comment]
I would like to work on this issue.

**Comment by swat1998** [comment]
Go ahead!!

**Comment by infiniteoverflow** [comment]
@swat1998  Should the scrollable cards be horiz or vertical??

**Comment by himanshusharma89** [comment]
I have developed this screen, if you like you can assign me this issue

**Comment by infiniteoverflow** [comment]
@swat1998 i have added the screen and made a PR
