### ISSUE TITLE
Editing Experience section in Home Page

### ISSUE THREAD

**Issue by sonalsk** [smaranjitghose/girlscript_app#161]
Suggested changes : 
1. Change parting line and make it more responsive
2. Link 'Read More' button to respective page
3. Edit information under Successful Projects and Events
4. Make section responsive

![Screenshot from 2020-03-17 17-01-33](https://user-images.githubusercontent.com/51206050/76852361-2637b680-6871-11ea-89d4-7117905c87e0.png)

**Comment by sakshi1499** [comment]
We (team femmetech) would like to do this.

**Comment by smaranjitghose** [comment]
@sonalsk  @sakshi1499 .. the website is being maintained at https://github.com/smaranjitghose/girlscript_chennai_website
Please follow up from there
