### ISSUE TITLE
Add Padding and Organizing Contact Us Page

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#166]
Add padding to the page.
Re-style the theme of the page.
Add AppBar.
Remove the logo of GSSoC and put appropriate content in the AppBar.
Add Github handle link.
Use this facebook logo. (The color accent in the existing one is incorrect)

![fb_link](https://user-images.githubusercontent.com/42760850/76999307-6df73480-697c-11ea-8865-7f4f4cbc03c0.png)

**Comment by himanshusharma89** [comment]
Hey @ousnik , these issues are in **ContactUs** page, I guess?

**Comment by himanshusharma89** [comment]
Hey @ousnik @smaranjitghose I would like to work on this.
