### ISSUE TITLE
Update the Projects page

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#168]
- The existing projects page just has horizontally scrollable cards with github logos.
- Modify the existing page and upload mock data for display and create hyperlink to github repository of each project. 
- Add a Card that opens the github handle of girlscript.

Example (This is just to give you an idea. No need to make this exactly) :

![image](https://user-images.githubusercontent.com/42760850/77000255-13f76e80-697e-11ea-8b26-c075c96a872d.png)

**Comment by himanshusharma89** [comment]
Hey @ousnik @smaranjitghose , I would like to work on this.

**Comment by infiniteoverflow** [comment]
@ousnik sir , i would like to work on this issue :)

**Comment by himanshusharma89** [comment]
Hey @infiniteoverflow , I have developed the Project page, so can you modify it?

**Comment by infiniteoverflow** [comment]
Yesss i can :)
