### ISSUE TITLE
ReDesign the AppBar

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#169]
redesign the appbar in the homepage.
Add a user icon to it for logging in when clicked.

**Comment by Diya8** [comment]
@ousnik I am interested in working on this issue? Can you please assign it to me?

**Comment by Diya8** [comment]
@ousnik Just to clarify... I have to add a user icon to the app bar at the bottom of the page right? What page should it go to when clicked?

**Comment by ousnik** [comment]
> 
> 
> @ousnik Just to clarify... I have to add a user icon to the app bar at the bottom of the page right? What page should it go to when clicked?

AppBar exists at the top of the page. Right now Just make the iconbutton...Dont link it to any page.

**EXAMPLE:**

![Annotation 2020-03-20 154511](https://user-images.githubusercontent.com/42760850/77154510-da2f8080-6ac1-11ea-87c5-35c61bbe6555.png)

**Comment by Diya8** [comment]
I forked the project and ran it on android studio. I can't see the app bar as you mentioned. I can only see a bar at the bottom. 
![WhatsApp Image 2020-03-21 at 5 38 58 PM](https://user-images.githubusercontent.com/42782061/77226036-010db580-6b9b-11ea-9bfb-f7869ede61dc.jpeg)

**Comment by Diya8** [comment]
@ousnik or should i create a new appbar?

**Comment by ousnik** [comment]
> 
> 
> @ousnik or should i create a new appbar?

Create one then

**Comment by Diya8** [comment]
@ousnik i made a pr. please review

**Comment by himanshusharma89** [comment]
Hey @smaranjitghose @ousnik , If this is not yet done, can I work on this issue?

**Comment by Diya8** [comment]
I'm currently working on it

**Comment by himanshusharma89** [comment]
Oh Okay!
