### ISSUE TITLE
Clean app folder 

### ISSUE THREAD

**Issue by sukkritsharmaofficial** [smaranjitghose/girlscript_app#174]
Remove unnecessary files and create git ignore file.

**Comment by sameeerkashyap** [comment]
I'd like to work on this

**Comment by PratilipiAich** [comment]
I would like to work on this issue.

**Comment by sukkritsharmaofficial** [comment]
For the first week im assigning it to @Sameerkash . @PratilipiAich you can take over from him next week.

**Comment by sameeerkashyap** [comment]
Can you please explain ? I didn't get you by first and second week. Does is mean I'll only have to maintain for this week ?

**Comment by sukkritsharmaofficial** [comment]
@Sameerkash go ahead, and make sure that you dont misplace any important file. This is something that would require a weekly check when the new files are added. So for now, for the first week maybe after 3-4 days you come back again and see if there are new unimportant files and clean them up.

**Comment by sameeerkashyap** [comment]
Okay got it cool. And do I add the  .gitignore outside the directory ? Like is there a soec of what all I should include ? Or shall I follow normal terms and ignore only non essential and imitating things

**Comment by sukkritsharmaofficial** [comment]
Yes define the gitignore file outside the dir and yes follow normal terms and see whatever you think is not useful and few replicated files need to be removed.
