### ISSUE TITLE
Add custom icon pack

### ISSUE THREAD

**Issue by swat1998** [smaranjitghose/girlscript_app#18]
Add a custom icon pack with popular icons of apps e.g. linked in, github, etc.

**Comment by himanshusharma89** [comment]
Assign me this issue.

**Comment by AjinkyaTaranekar** [comment]
Hello @swat1998, I would like to add the custom icon pack! Please assign me this issue.

**Comment by bharat-1809** [comment]
@swat1998 I would like to work on this issue, please assign me this issue

**Comment by smaranjitghose** [comment]
@AjinkyaTaranekar  Go forward
