### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_app#204]
**Is your feature request related to a problem? Please describe.**
Splash Screen with animation and the gradient given

**Describe the solution you'd like**
Splash Screen
If possible a complete walkthrough of the app

**Additional context**
describe
1. about the app.
2. explain about navigation.
3. creating UI for the elements in-app.

Please mention the work you are doing before I assign u this task.
**Follow the UI Strictly**

Any files needed Just Contact me or other mentors

**Comment by himanshusharma89** [comment]
Hey, @anushbhatia I would like to work on this.

**Comment by anushbhatia** [comment]
Now u can make enhancement by adding vectors to it.

**Comment by bharat-1809** [comment]
Can I work on this?

**Comment by himanshusharma89** [comment]
> Now u can make enhancement by adding vectors to it.

What type of vectors?

**Comment by anushbhatia** [comment]
So that it looks more attractive to look through apps like frapp,udemy
either Adding loader

**Comment by smaranjitghose** [comment]
@himanshusharma89 Is the final work for this issue done?

**Comment by himanshusharma89** [comment]
> @himanshusharma89 Is the final work for this issue done?

Yes, it's already done
