### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_app#206]
**Describe the solution you'd like**
Make the Login screen as same as the _mockup_

**Contents**
1. Use Proper fonts 
2. Use already existing icons on the page.
3. For the UI elements refer to the website [www.flaticon.com](https://www.flaticon.com/).

**Please mention the work you are doing before I assign u this task.**
**Follow the UI Strictly**

Any files needed Just Contact me or other mentors

**Comment by bharat-1809** [comment]
I would like to work on it

**Comment by anushbhatia** [comment]
Finish your previous issues then I can assign you this one.

**Comment by minolipvartak** [comment]
I would like to work on this issue @anushbhatia

**Comment by shubhamaniket** [comment]
I would like to work on this @anushbhatia .

**Comment by anushbhatia** [comment]
OK guys so distribute the work among yourself I will assign all of this task

**Comment by shreyakapoor08** [comment]
Hey, Can I work on this issue ?

**Comment by anushbhatia** [comment]
You are currently working on team page right now so finish that up

**Comment by abhishekgupta368** [comment]
can I do it?

**Comment by anushbhatia** [comment]
Coordinate with @minolipvartak @shubhamaniket

**Comment by Adyasha8105** [comment]
I would like to work on this issue.

**Comment by minolipvartak** [comment]
Hey @anushbhatia . I see there is a custom background for the Login page. Can you provide me its file?

**Comment by anushbhatia** [comment]
Send me your email id

**Comment by minolipvartak** [comment]
minoli879@gmail.com

**Comment by abhishekgupta368** [comment]
Email: abhigupta9087@gmail.com

**Comment by imyashadulkar** [comment]
Hello @anushbhatia  I would like to work on this screen

**Comment by abhishekgupta368** [comment]
My laptop is not able to run flutter application. it heats up and shut down. what should I do?

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue if its not done. Please assign this to me as part of GSSoC'20

**Comment by anushbhatia** [comment]
Go ahead @Rukmini-Meda

**Comment by Rukmini-Meda** [comment]
UI is sufficient for this issue right! Will there be a separate issue for backend using firebase?

**Comment by Rukmini-Meda** [comment]
The background has an image, right... or should I only keep the gradient because I couldn't find that image in assets. If there is any corresponding image, please let me know.

**Comment by Rukmini-Meda** [comment]
I also have one more doubt. Now when the app runs, after splash screen timing, its navigated to sign up screen immediately and I am not able to go back, so how should I keep the navigation to login page? Should I show login page after splash screen? The other screens are also not accessible.

**Comment by Rukmini-Meda** [comment]
Please reply soon.

**Comment by anushbhatia** [comment]
keep login screen after splash screen. For colours, I have uploaded the gradients in the readme file just check that.
