### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#216]
I would like to create the Home screen as same as the mockup.

**Comment by suryadevsingh** [comment]
I would like to work on this .

**Comment by anushbhatia** [comment]
Make action on click of read more button.
enable voice to speak.
Reduce the shadow size 
x:0 y:3 B:15

**Comment by anushbhatia** [comment]
Orange line shadow to
X:0 Y:3 b:6

**Comment by anushbhatia** [comment]
make the proper file structure in the lib folder cards and navigation 
Add comments if possible to your code structure
