### ISSUE TITLE
Sign Up Screen

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#218]
**Describe the solution you'd like**
Make the Login screen as same as the _mockup_

**Contents**
1. Use Proper fonts 
2. Use already existing icons on the page.
3. For the UI elements refer to the website [www.flaticon.com](https://www.flaticon.com/).

**Please mention the work you are doing before I assign u this task.**
**Follow the UI Strictly**

If you need any help with the UI contact @anushbhatia, @swat1998  @ousnik

**Comment by bharat-1809** [comment]
I would like to work on it

**Comment by smaranjitghose** [comment]
Cool! It's being assigned to you for the next 4 days.

Do give a PR and coordinate as per the suggestions given by the mentors

**Comment by swat1998** [comment]
@bharat-1809 Please do strictly follow mock up given in the repository.

**Comment by bharat-1809** [comment]
> @bharat-1809 Please do strictly follow mock up given in the repository.

Sure
