### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#219]
**Describe the solution you'd like**
Make the Login screen as same as the _mockup_

**Contents**
1. Use Proper fonts 
2. Use already existing icons on the page.
3. For the UI elements refer to the website [www.flaticon.com](https://www.flaticon.com/).

**Please mention the work you are doing before we assign u this task.**
**Follow the UI Strictly**

**Comment by bharat-1809** [comment]
I was already working on this previously so can I go forward with it ?

**Comment by Anushka-shukla** [comment]
Please assign me this issue !!

**Comment by smaranjitghose** [comment]
@bharat-1809 Could you please work on the Sign-Up page issue I assigned you now

**Comment by smaranjitghose** [comment]
@Anushka-shukla For the next 5 days assigned to you.

**Comment by bharat-1809** [comment]
> @bharat-1809 Could you please work on the Sign-Up page issue I assigned you now

Yeah Sure

**Comment by anushbhatia** [comment]
@Anushka-shukla Update on this Page

**Comment by Anushka-shukla** [comment]
Solving the errors..

**Comment by anushbhatia** [comment]
Any screenshot of screen?

**Comment by sheen404** [comment]
Can I work on this issue?

**Comment by ousnik** [comment]
> 
> 
> Can I work on this issue?

go ahead.

**Comment by sheen404** [comment]
> > Can I work on this issue?
> 
> go ahead.

What specifically needs to be done?

**Comment by ousnik** [comment]
> 
> 
> > > Can I work on this issue?
> > 
> > 
> > go ahead.
> 
> What specifically needs to be done?

Check the mock-up and make the team page exactly as seen. We will provide u the assets when u need it. Also check the description of this issue.

**Comment by sheen404** [comment]
![Screenshot_1588849316](https://user-images.githubusercontent.com/52331477/81287406-54bb5c00-9080-11ea-843d-4cd8a8c55e04.png)
