### ISSUE TITLE
Create card carousel for home page.

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#22]

**Comment by himanshusharma89** [comment]
I would like to take this issue.

**Comment by ousnik** [comment]
What would you like to display in the cards?

**Comment by himanshusharma89** [comment]
You can provide me with the data as shown in this image.
https://raw.githubusercontent.com/sukkritsharmaofficial/PyDepo/master/Girlscript%20ui/Home.png

**Comment by Anushka-shukla** [comment]
Anyone has been assigned this issue yet? I would like to work upon this.

**Comment by goyalmuskan** [comment]
Please assign me with this issue if it's still unassigned! @smaranjitghose

**Comment by smaranjitghose** [comment]
Assigned to @goyalmuskan for next 7 days

**Comment by goyalmuskan** [comment]
Can you please provide me with the data? @smaranjitghose
