### ISSUE TITLE
Analytics Script

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#220]
# Tasks: 
- Count the number of Pull Requests
- Count the number of Issues
- Count the number of Pull Requests Merged separately
- Create a log file of the Pull Requests: name, merged or not, linked issue, labels, who raised it

**Comment by SAITARUN55** [comment]
I would like to work on this issue

**Comment by smaranjitghose** [comment]
Can you do it for the Pull requests within a week?

**Comment by SAITARUN55** [comment]
Will try and update the same with you

**Comment by smaranjitghose** [comment]
Cool! take your time and if you need help @swat1998 can help you out
