### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#223]
@swat1998 
I would like to create the Events Page of the application.

**Comment by anushbhatia** [comment]
Please don't create any issue without contacting a mentor.

**Comment by himanshusharma89** [comment]
> Please don't create any issue without contacting a mentor.

@anushbhatia I have contacted @swat1998 for this.

**Comment by anushbhatia** [comment]
Currently mockup has been not given so if u are making something don't create a issue or pr before showing us.

**Comment by himanshusharma89** [comment]
@swat1998 told me to follow mockups in the Mockup folder, as other screens have been assigned, I started working on the Events mockup in that folder.
And I have showed the developed screen to @swat1998
@anushbhatia

**Comment by anushbhatia** [comment]
Please refer to the Readme file only and ignore the rest of the mockups given

**Comment by himanshusharma89** [comment]
So which screen should I work on? Every screen is assigned. And I have completed the Home screen and will make a PR soon.
