### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_app#231]
# Tasks to be performed:
Follow the mockup to create the events page.

Have the elements int the carousel Dynamic. We don't need static elements

__Please strictly follow the UI given and feel free to contact any of the mentors for help__
Any problems related to custom elements. Feel free to contact me on slack.

**Comment by rajnis09** [comment]
I would like to work on it. Please assign me this task.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue if it's not done yet. Please assign this to me as part of GSSOC'20.

**Comment by anushbhatia** [comment]
it is done but u can add enhance this feature.

**Comment by smaranjitghose** [comment]
@Rukmini-Meda Are you working on any enhancement for this issue?

**Comment by Rukmini-Meda** [comment]
@smaranjitghose No, are there any other issues based on flutter that I can grab?

**Comment by smaranjitghose** [comment]
This entire app is built using Flutter, if you have any enhancements to propose to the design or add some features, discuss it with @ousnik or @anushbhatia and give a pr
