### ISSUE TITLE
Add GitHub actions for the project.

### ISSUE THREAD

**Issue by aashimgarg** [smaranjitghose/girlscript_app#235]
# Tasks to be performed:

We can add github actions for the betterment of the project.

Should i start working?

**Comment by smaranjitghose** [comment]
List the actions(at max 6) here with their purpose. Only after being approved, proceed with separate PRs.

**Comment by Adyasha8105** [comment]
CAN I?

**Comment by aashimgarg** [comment]
We can have:-
1. greetings
2. label-merge-conflicts
3. foul language
4. dart package analyzer

**Comment by smaranjitghose** [comment]
Go ahead with #1,#2,#3
