### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by Aman-Codes** [smaranjitghose/girlscript_app#244]
**Description of the enhancement**
* The link of code of conduct file in readme.md is broken.
* Remove the unwanted "s" after girlscript app

**Screenshots**
![Screenshot_20200426-101157_1](https://user-images.githubusercontent.com/54680709/80298187-4713f580-87a7-11ea-8f20-2a8b553280ec.jpg)

**Comment by ousnik** [comment]
Thank You for bringing this to our notice.
However, this being an issue that is too trivial there will not be any points assigned to it.
It has been fixed.
