### ISSUE TITLE
Add a ListView of Cards to Events

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#25]
Create and optimized listview in the events page. The items in the listview have to be cards. 
Preferably the cards should be simplistic yet stylish containing the following details about event:

- Name of event
- Organizer
- Date
- Time
- Venue
- Fee
- A button to register for it

**Comment by himanshusharma89** [comment]
I would like to work on this issue.

**Comment by bharat-1809** [comment]
@ousnik I would like to work on this issue.

**Comment by bharat-1809** [comment]
Thanks @smaranjitghose for assigning me this issue
