### ISSUE TITLE
Bug in signup

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_app#250]
Avoid overflow property here. 
![Screenshot_20200503_012603_com example communityappboilerplate](https://user-images.githubusercontent.com/40017559/80891110-82e71780-8cdf-11ea-9390-275bec2fe399.jpg)

**Comment by sheen404** [comment]
Can I be assigned to this issue?

**Comment by anushbhatia** [comment]
Sure can u do one more thing for time being on click of signin redirect to home page

**Comment by anushbhatia** [comment]
You have done this so should I close this

**Comment by sheen404** [comment]
> You have done this so should I close this

Yes, sure.
