### ISSUE TITLE
Fix the error in the milestone page

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#254]
![Screenshot_1589057948](https://user-images.githubusercontent.com/42760850/81484792-28613480-9266-11ea-9922-8665861e8bb6.png)

**Comment by sheen404** [comment]
Please assign me this issue.

**Comment by sheen404** [comment]
![Screenshot_1589131603](https://user-images.githubusercontent.com/52331477/81506083-99115b00-9311-11ea-9770-dd70aa36404c.png)

**Comment by ousnik** [comment]
@sheen404 is it working for you?

**Comment by sheen404** [comment]
> @sheen404 is it working for you?

I fixed it. Just sharing the screenshot.

**Comment by ousnik** [comment]
> 
> 
> > @sheen404 is it working for you?
> 
> I fixed it. Just sharing the screenshot.

Great! Can you please make the PR asap. 

Note: It is preferable if you make seperate PRs for solving 2 different issues because points for each issue is allotted seperately.

**Comment by nerdynikhil** [comment]
I fixed it. Made a PR.

**Comment by Ishikagarg-ig** [comment]
Can i take this issue?

**Comment by Ishikagarg-ig** [comment]
As i have tested the app this issue only arises when I have used GoogleSingIn. If i am manually putting details then its working fine.

**Comment by Ishikagarg-ig** [comment]
Have you added your android debugkey SHA-1 fingerprints in your firebase console and updated google-services.json file after adding them?

**Comment by himanshusharma89** [comment]
This error is caused due to wrong mapping of User info with Google Auth, closing it. #275
