### ISSUE TITLE
Overflow in Events Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/girlscript_app#255]
![Screenshot_20200510_192732_com example communityappboilerplate](https://user-images.githubusercontent.com/40017559/81501241-f34ff300-92f4-11ea-84f5-80609b71e51b.jpg)
Overflow of buttons add a carousel there so that it can slide and you can mutiple slides there

**Comment by sheen404** [comment]
Can I be assigned this issue?

**Comment by Anirudhk07** [comment]
Can I take this?

**Comment by Ishikagarg-ig** [comment]
can I take this issue?

**Comment by anushbhatia** [comment]
Sure go on how long will you take to make a pr

**Comment by Ishikagarg-ig** [comment]
i fixed the issue!!
