### ISSUE TITLE
Add content to Home Page

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#256]
Update the existing blueprint of the home page with relevant content. 

Refer to the website for content:
[https://girlscriptboilerplate.netlify.app/](url)

**Comment by Rukmini-Meda** [comment]
Can I work on this issue? Please assign this to me as part of GSSoC'20.

**Comment by Rukmini-Meda** [comment]
@ousnik Can you help me to navigate to home screen? It requires userid to create its object. So, i am not able to navigate to it. Please reply soon.
