### ISSUE TITLE
Pre Sign Up Slider

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#270]
A full screen intro slider when user freshly install the app before registration.

**Comment by SirusCodes** [comment]
Can you give me more details about this?

**Comment by himanshusharma89** [comment]
@SirusCodes A full screen intro slider when user freshly install the app before registration.

**Comment by SirusCodes** [comment]
Ok I can do this you can assign me this and provide me with assets

**Comment by himanshusharma89** [comment]
Hey @SirusCodes we don't have a specific asset you can use some vectors design for this.

**Comment by SirusCodes** [comment]
@himanshusharma89 how does this looks?
![Intro screen](https://user-images.githubusercontent.com/50910066/94987810-c1327c80-0586-11eb-93d8-ef720248c952.gif)

**Comment by himanshusharma89** [comment]
Yeah @SirusCodes Looks good, create a PR. I hope you used dynamic methods for creating this.

**Comment by SirusCodes** [comment]
> Yeah @SirusCodes Looks good, create a PR. I hope you used dynamic methods for creating this.

Yes yes

**Comment by himanshusharma89** [comment]
Cool
