### ISSUE TITLE
Firebase GitHub Authentication

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#272]

**Comment by Anirudhk07** [comment]
Can I take this ?

**Comment by anushbhatia** [comment]
Work on LinkedIn authentication

**Comment by Anirudhk07** [comment]
Sure @anushbhatia

**Comment by rish07** [comment]
Hey @himanshusharma89, if the feature request still exists, I would like to work on it during hacktoberfest.

**Comment by himanshusharma89** [comment]
Sure, @rish07. We are planning to maintain this repository for Hacktoberfest.

**Comment by himanshusharma89** [comment]
Hey @rish07, are you working on this issue? Should I assign it to you? And if you need a reference do let me know.

**Comment by rish07** [comment]
Hey, @himanshusharma89, I have actually completed the code. Will create a PR in a while.

**Comment by himanshusharma89** [comment]
@rish07 Perfect! and BTW It is implemented with Firebase, right?

**Comment by rish07** [comment]
Yes, @himanshusharma89. You will just have to change the CLIENT ID and CLIENT SECRET in the code which you'll get when you create a GitHub oauth app. 

I will put these instructions in the PR.

**Comment by himanshusharma89** [comment]
Great! @rish07. But we already have the ID and SECRET, I'll share those with you but before that share your email, I'll add you to the firebase console.

**Comment by rish07** [comment]
@himanshusharma89 it's rishirajsinghchhabra@gmail.com
