### ISSUE TITLE
Code enhancement in Teams Page

### ISSUE THREAD

**Issue by imyashadulkar** [smaranjitghose/girlscript_app#274]
Path: community_app_boilerplate/lib/ui/screens/Teams.dart

We have stored the Teams Images in assets. We could use free storage services and host it on a server and instead of **AssetImage** we could use it **CacheNetworkImage** 
It would reduce app size and also since it is a cache network Image so the image will be loaded only when the image is changed, other times the widget would directly take the image from the cache itself. 
Also wherever you have used Network Image. I would like to use the **CacheNetworkImage** widget.
If you allow me, I would like to do these changes.

**Comment by himanshusharma89** [comment]
Sure @elaishane, should I assign it to you?

**Comment by lordvins226** [comment]
i can take this. you can upload images on free storage and give link?

**Comment by imyashadulkar** [comment]
Yes

**Comment by himanshusharma89** [comment]
@elaishane You are saying yes to work on this issue?

**Comment by imyashadulkar** [comment]
Yes

**Comment by imyashadulkar** [comment]
@himanshusharma89 I would be needing a storage location, it their image links.

**Comment by himanshusharma89** [comment]
@elaishane Do you have a platform in mind for the deployment of the images?

**Comment by imyashadulkar** [comment]
I think github would do.

**Comment by himanshusharma89** [comment]
Okay @elaishane, so I guess all the assets are already uploaded you can work on it right away check out the assets folder.

**Comment by imyashadulkar** [comment]
Sure. Thank you

**Comment by himanshusharma89** [comment]
Hey @elaishane, any update? and should I assign it to you?

**Comment by imyashadulkar** [comment]
I am working on it. It would be completed by tomorrow evening

**Comment by himanshusharma89** [comment]
Thanks for the update @elaishane. Assigning it to you.

**Comment by imyashadulkar** [comment]
Hey, @himanshusharma89 I will be needing a link for the images. Like Twitter, Facebook, GitHub but separate repo. A link that would not change even with new changes

**Comment by himanshusharma89** [comment]
Hi @elaishane, what about these links:
https://img.icons8.com/fluent/50/000000/github.png
https://img.icons8.com/color/48/000000/twitter.png
https://img.icons8.com/color/48/000000/linkedin.png

You can directly use them in NetworkImage

**Comment by imyashadulkar** [comment]
Ok

**Comment by Saransh-cpp** [comment]
Hey @himanshusharma89 , can I work on this issue as no one is working on it?

**Comment by himanshusharma89** [comment]
Sure @Saransh-cpp

**Comment by Saransh-cpp** [comment]
Should I create a new branch? Also after adding cached_network_image dependency in the pubspec.yaml file and running the code in my system, it automatically edited .idea/libraries/Dart_Packages.xml file, should I add this in git or should I push changes without adding this edited file, keeping the old file? Please guide

**Comment by himanshusharma89** [comment]
@Saransh-cpp Yeah, create a new branch. And the changes you mentioned are already ignored using .gitignore. You can start working on the issue.
