### ISSUE TITLE
Google Sign In OAuth2 Security Flaw

### ISSUE THREAD

**Issue by rish07** [smaranjitghose/girlscript_app#275]
Hey @himanshusharma89 
I was going through the app and came across the following issue:
1) I pressed sign in with google on the sign-up page.
2) Didn't select an account and pressed back.
3) The app redirected me to the Dashboard with null values with though I wasn't authenticated.

I am attaching a screenshot of the app being logged in without auth. 
![WhatsApp Image 2020-09-29 at 1 50 59 AM](https://user-images.githubusercontent.com/49035175/94482084-600d5080-01f6-11eb-95ec-3e84faec5d53.jpeg)

I would like to work on this issue as well along with the Github auth implementation during Hacktoberfest.

**Comment by himanshusharma89** [comment]
Go ahead @rish07. Assigning this issue to you.

**Comment by himanshusharma89** [comment]
Any update @rish07?

**Comment by rish07** [comment]
Hey @himanshusharma89,
I actually have an exam tomorrow so I'll fix it by tomorrow evening.

**Comment by himanshusharma89** [comment]
Okay, @rish07. Good luck.

**Comment by himanshusharma89** [comment]
Also, the null value is still there after successful sign-up, but it doesn't occur if we restart the app. I checked the mapping methods, it is fine but still, the issue is there. Have a look into this also.

**Comment by rish07** [comment]
Sure

**Comment by arbazdiwan** [comment]
@himanshusharma89, I would like to solve this issue if @rish07 is facing any problems.

**Comment by himanshusharma89** [comment]
@arbazdiwan, @rish07 will work on it and update us soon

**Comment by arbazdiwan** [comment]
ok Himanshu
