### ISSUE TITLE
Issue Labeler Workflow

### ISSUE THREAD

**Issue by himanshusharma89** [smaranjitghose/girlscript_app#279]
create a GitHub Action which will automatically label all the new issues created with the Hacktoberfest label.

**Comment by lordvins226** [comment]
Hello can you provide more details for this issue?

**Comment by himanshusharma89** [comment]
@lordvins226 Check this, create a GitHub Action which will automatically label all the new issues created with the Hacktoberfest label.

**Comment by lordvins226** [comment]
Okay. I will try

**Comment by himanshusharma89** [comment]
Great @lordvins226, assigning it to you.

**Comment by himanshusharma89** [comment]
Hey @lordvins226, any update?

**Comment by lordvins226** [comment]
Yes. Sorry for late.

**Comment by lordvins226** [comment]
For the greetings file, what's the action?

**Comment by himanshusharma89** [comment]
This the greetings action: https://github.com/smaranjitghose/girlscript_app/blob/master/.github/workflows/greetings.yml. You can fix the error and create a PR

**Comment by lordvins226** [comment]
> This the greetings action: https://github.com/smaranjitghose/girlscript_app/blob/master/.github/workflows/greetings.yml. You can fix the error and create a PR

i will try this

**Comment by himanshusharma89** [comment]
Any update? @lordvins226

**Comment by lordvins226** [comment]
> Any update? @lordvins226

Hi. I made test for greetings workflow, but actions use in file check if it's the contributors first time for create issue or pull request. it's this task we want to achieve?

**Comment by himanshusharma89** [comment]
@lordvins226 The main task was to create the labeler action. the greetings one was proposed by you. No PR is submitted for the labeler issue

**Comment by lordvins226** [comment]
i already make PR for labeler issue. it's still about greetings PR

**Comment by himanshusharma89** [comment]
@lordvins226 Oh my bad, I am closing this issue. Create a new issue and I'll assign it to you and yes this is the task.

> Hi. I made test for greetings workflow, but actions use in file check if it's the contributors first time for create issue or pull request. it's this task we want to achieve?
