### ISSUE TITLE
Missing , and Empty RichText

### ISSUE THREAD

**Issue by rabeehrz** [smaranjitghose/girlscript_app#3]
Hello.

I was just setting up the environment and found some build errors.

- Missing , at line 120

https://github.com/smaranjitghose/girlscript_app/blob/da90ebed8aed250300916303d6c2daf253e22db0/lib/home.dart#L117-L123

- Empty Rich Text at line 166

https://github.com/smaranjitghose/girlscript_app/blob/da90ebed8aed250300916303d6c2daf253e22db0/lib/home.dart#L164-L168

I would like to fix these issues as a part of GSSoC '20.

**Comment by smaranjitghose** [comment]
Go Ahead
