### ISSUE TITLE
Create the Basic Homepage for GirlScript Chennai website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#30]
Create the main ```index.html``` file in the https://github.com/smaranjitghose/girlscript_app/tree/master/website directory

**Comment by rabeehrz** [comment]
Hello. I’d like to work on this issue. Please assign this to me.

**Comment by himanshusharma89** [comment]
Hey! I would like to work on this issue.

**Comment by smaranjitghose** [comment]
@himanshusharma89 Go ahead

**Comment by smaranjitghose** [comment]
also make sure the images that you use are catered for GirlScript Chennai only..Try to design them..have a separate assets folder so that in future we can update the design

**Comment by rabeehrz** [comment]
@smaranjitghose May I please know why I wasn’t assigned to this issue?

**Comment by smaranjitghose** [comment]
@rabeehrz I wanted to work on the update of the home page and @himanshusharma89  has already given so many updates for the app within a short time.Hence I assigned it to him so that once the basic home page is done you and the others can work on integrating other stuff

**Comment by rabeehrz** [comment]
@smaranjitghose Yeah okay. I think it should be done using some Framework though.

**Comment by smaranjitghose** [comment]
Once @himanshusharma89 is done is with this..I'll create an Update issue..you can take over from there

**Comment by rabeehrz** [comment]
@smaranjitghose That sounds good. ♥️

**Comment by krabhisharma** [comment]
hey I would like to work on this
