### ISSUE TITLE
Create the events page for GirlScript Chennai website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#31]

**Comment by rabeehrz** [comment]
I’d like to work on this issue.

**Comment by smaranjitghose** [comment]
Assigned..Make sure you use the https://github.com/smaranjitghose/girlscript_app/tree/master/website directory

**Comment by rabeehrz** [comment]
@smaranjitghose I guess I should wait for the home page to be created so that I can use that as a template?

**Comment by smaranjitghose** [comment]
The home page is done..please proceed
