### ISSUE TITLE
Create the Contact us page for GirlScript Chennai website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#32]

**Comment by AjinkyaTaranekar** [comment]
I would like to work on this issue. @smaranjitghose will this use Flutter Web?

**Comment by smaranjitghose** [comment]
No we are creating a separate website

**Comment by AjinkyaTaranekar** [comment]
So, just HTML, CSS and JS?

**Comment by smaranjitghose** [comment]
Ya..for now

**Comment by AjinkyaTaranekar** [comment]
Ohkay, then I would like to work upon.

**Comment by manan-bedi2908** [comment]
I would like to work on this issue

**Comment by sanket9918** [comment]
I would like to work on it on React. I can also help in converting it to a component for reusability.

**Comment by smaranjitghose** [comment]
@AjinkyaTaranekar has been assigned  this for a week..once his PR is reviewed..
 @manan-bedi2908 and @sanket9918 ..the mentors will raise some specific issues for the events page and you can proceed then

**Comment by HarshMehta2468** [comment]
I'd like to work on this issue too.

**Comment by smaranjitghose** [comment]
@AjinkyaTaranekar the intial home page is please check and proceed  accordingly  with the contact us page

**Comment by smaranjitghose** [comment]
@mySTRiouscoder sure..once  the mentors raise an issue for updating  the page..you  can start off

**Comment by vinay2214** [comment]
i would like to work on it

**Comment by AjinkyaTaranekar** [comment]
@smaranjitghose Sure, I am currently making its UI, and I want a suggestion in the feedback form, should I connect it to google sheets for the response.

**Comment by vinay2214** [comment]
yes you can.

**Comment by AjinkyaTaranekar** [comment]
@smaranjitghose I tried to connect the form to google sheets, but data is not being sent into the sheets. Can you help?

**Comment by vinay2214** [comment]
yes can I try?

**Comment by smaranjitghose** [comment]
@AjinkyaTaranekar What error are you facing?.. @vinay2214 try it
