### ISSUE TITLE
Create a Blog Section in the Website that can be integrated with Medium

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#37]

**Comment by dwvicy** [comment]
I'd like to work on this

**Comment by goyalmuskan** [comment]
I want to work on the issue. Please assign me the same. @smaranjitghose @sukkritsharmaofficial

**Comment by smaranjitghose** [comment]
@dwvicy go forward...take the next 8 days..if you can't  complete  it then it shall be reassigned to @goyalmuskan

**Comment by smaranjitghose** [comment]
@dwvicy the main home page is up..create a separate page for blog..discuss with the mentors in the slack channel if you  need any assistance ...Give  a PR for that first

**Comment by smaranjitghose** [comment]
After that work on integration  with Medium..

**Comment by dwvicy** [comment]
So would I have to embed the blog onto the website to just redirect?

**Comment by dwvicy** [comment]
so I've made a separate blog page, but inorder to integrate it with medium i would need access to the medium account for the website. Is there one already or should I create one?

**Comment by smaranjitghose** [comment]
https://medium.com/girlscript-chennai 
Use this please @dwvicy
