### ISSUE TITLE
Create Icons and Other Images for the GirlScript Chennai website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#39]
Inside the website folder create a folder assets and store it there. 
Please make 3 at a time and give a PR..so that others can be given chance as well

**Comment by goyalmuskan** [comment]
Please assign me this issue, I want to work on it. @smaranjitghose

**Comment by sanket9918** [comment]
I also want to work on the same @smaranjitghose

**Comment by smaranjitghose** [comment]
For the next 7 days it's assigned  to @goyalmuskan

**Comment by goyalmuskan** [comment]
Can you please brief me on what's required of me? What kind of icons and images? @smaranjitghose

**Comment by smaranjitghose** [comment]
@goyalmuskan  could you please speak to me or any of the others in DM in slack...That way its easier to share

**Comment by HarshMehta2468** [comment]
May i work on this issue as well?
