### ISSUE TITLE
Improve the documentation for GirlScript Chennai website 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#41]
Start with updating with some resources to start with and then as the other members build on give a complete description of the same

**Comment by Aju100** [comment]
@smaranjitghose  can u assinged for this.

**Comment by Swati0604** [comment]
@smaranjitghose Please assign me this work.

**Comment by dwvicy** [comment]
I can work on this as this would help me understand the issue I'm working on currently.

**Comment by smaranjitghose** [comment]
@Aju100  and  @dwvicy  Work together  for this and give separate PRs for adding  different  section

**Comment by Aju100** [comment]
@dwvicy  hello we should divide our tasks so we can work together

**Comment by smaranjitghose** [comment]
Please use  the slack  DMs for such conversations

**Comment by smaranjitghose** [comment]
The initial  Home Page is up..you  can use  it for reference
As of now we plan:
Home  page 
Events  page
Achievements  page
Team page
Blog page(redirecting  to medium)
Contact us page
