### ISSUE TITLE
Create an achievements  page for GirlScript Chennai  website 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#50]
This is so that we can potray our members achievements  in various hackathons/competitions/conferences

**Comment by manan-bedi2908** [comment]
I would like to work on this issue

**Comment by himanshusharma89** [comment]
I would like to work on this.

**Comment by Dadaabhis** [comment]
I woild like. To work on this..

**Comment by atrip10** [comment]
i would like to work on this

**Comment by smaranjitghose** [comment]
@atrip10 @himanshusharma89 @manan-bedi2908 work together and make separate PRs for different parts of the page..I would suggest that the page have posts(that can be done only by admins) with a headline and a small description..On Clicking on the headline..it should redirect to a separate page for it having more description,places to put picture and places to put relevant social media links

**Comment by manan-bedi2908** [comment]
Ok, I'll make the achievements page and make posts with the help of cards
where I will have an option for read more as well as update.

**Comment by manan-bedi2908** [comment]
And in the update page, we can have places for adding image and
description. That thing, other two people can do. I will make a pull
request within two days for the start of Achievements page

**Comment by smaranjitghose** [comment]
@atrip10 
The website has been shifted to https://github.com/smaranjitghose/girlscript_chennai_website
as a separate project for GSSOC..Please checkout the codebase there and continue contributing there..The issues will be raised shortly there...Meanwhile, You are welcome to raise your own issues there
