### ISSUE TITLE
Create a events description page

### ISSUE THREAD

**Issue by ousnik** [smaranjitghose/girlscript_app#58]
When tapping on a project item, it should be redirected to its description page. The data related to the tapped item has to be displayed. 
The page should have a very good design.
The following data should be displayed:
Name 
Organizer(with logo)
Description
Date Time Venue
Poster of the event
related links

Note: Prefer a hero animation for the logo of the organizer.

**Comment by infiniteoverflow** [comment]
@ousnik is it for web??

**Comment by himanshusharma89** [comment]
@ousnik 
I would like to work on this issue.

**Comment by ousnik** [comment]
This issue will be assigned after the event page first draft has been merged.

**Comment by himanshusharma89** [comment]
@ousnik 
Okay, till then you can assign someone for this issue.

**Comment by suryadevsingh** [comment]
I would like to work on this issue . i can make responsive and custom design for this in flutter with smooth transition and animations in 60fps . plzz assign this issue to me . @ousnik 
thanks

**Comment by Anushka-shukla** [comment]
I would like to work on this.
