### ISSUE TITLE
create a mockup for the entire app

### ISSUE THREAD

**Issue by algokun** [smaranjitghose/girlscript_app#6]
As there are no mockups for the app. Please create mockups for the app.

Its better to include the following pages for  UI
Login
Home
Signup
Events

**Comment by minolipvartak** [comment]
I want to work on this issue. I am intetested in designing pages for the app @algokun

**Comment by PratilipiAich** [comment]
I would also like to work on this. @algokun

**Comment by krabhisharma** [comment]
what is  mockups?

**Comment by algokun** [comment]
@smaranjitghose could you please check this issue?

**Comment by smaranjitghose** [comment]
@algokun if you can collab with the others who are making the  Home,Events,Achievements,Team  and Contact Us page and the mentors for some insight  into the actual  content..i don't  mind having this as a official  issue
