### ISSUE TITLE
Work on the Contributing.MD file for the App

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#62]
Push it to the root directory at the master branch

For References:

- https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

- https://github.com/atom/atom/blob/master/CONTRIBUTING.md

- https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

**Comment by himanshusharma89** [comment]
@smaranjitghose 
I would like to work on this issue.

**Comment by nishantsharma09** [comment]
@smaranjitghose  Can I work on this issue?

**Comment by nishantsharma09** [comment]
Hi @smaranjitghose. I have created the [PR #111](https://github.com/smaranjitghose/girlscript_app/pull/111) for this issue. Please review and let me know for any further changes.

**Comment by smaranjitghose** [comment]
Please don't use the entire README for the contributing file..Rather use a part of it and the Code of conduct for it..Also Put in some suggestions like:one should not change the path name,push to a test branch first,etc...highlighting the problems we faced due to such things...Please refer the above links as well and some other open source projects..Also subsequently update the README
