### ISSUE TITLE
GitHub Page for the Project 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#63]
- Learn how to create GitHub pages
- Create a GitHub page for this project  inside a folder ```doc``` at the root directory of the master branch
- Take up from the readme of the project to start with
- Make it appealing with whatever you love

**Comment by infiniteoverflow** [comment]
I would like to work on this

**Comment by smaranjitghose** [comment]
@infiniteoverflow Go Ahead..

**Comment by smaranjitghose** [comment]
Remove the HTML5 UP preset elements like the footer and the tab names..please
Use up the content on the ReadME to describe the project
Remove the Connect with us Section
Put a section for the Project admins and mentors
Put a section which dynamically shows the recent pull requests,issues,forks,star
Put a section that shows count of contributors
Have a separate file or something from where each of the contributors usernames can be fetched and displayed in a grid format or anything that looks fancy..Including yours

**Comment by nishantsharma09** [comment]
Shall i take this issue? @smaranjitghose
