### ISSUE TITLE
Work on the Home Page for the GirlScript Chennai Website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#64]
- Try to improve it as much as possible in terms of features and design
- Suggestions:
  - Add social media icons
  - Add location
  - Improve the logo

Please create separate pull requests for each feature you add

**Comment by HarshMehta2468** [comment]
Can you assign this issue to me @smaranjitghose ?

**Comment by HarshMehta2468** [comment]
@smaranjitghose i have updated the links of social media handles and sent a pull reqst !!
