### ISSUE TITLE
Add the Team Page section in the GirlScript Chennai home page 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#68]

**Comment by HarshCasper** [comment]
I would like to work on this issue as part of GSSOC'2020. I would be highly obliged if you can grant me permission to work on this issue @smaranjitghose

**Comment by goyalmuskan** [comment]
Please assign me this issue. @smaranjitghose @sukkritsharmaofficial

**Comment by goyalmuskan** [comment]
This is for website right?

**Comment by Anushka-shukla** [comment]
For the mobile app I would like to work on it.
please assign me this issue.

**Comment by aksayushx** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by smaranjitghose** [comment]
@Anushka-shukla mobile app
@goyalmuskan website

**Comment by smaranjitghose** [comment]
Refer:https://dscvit.com/team.html

**Comment by manan-bedi2908** [comment]
I would like to work on this issue
