### ISSUE TITLE
Improve the design of the social media icons in the footer of the GirlScript Chennai website. We need Instagram,Twitter,LinkedIN,Facebook

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#69]

**Comment by HarshCasper** [comment]
I would like to work on this issue as part of GSSOC'2020. I would be highly obliged if you can grant me permission to work on this issue @smaranjitghose

**Comment by gpsuhas20** [comment]
i would like to work on this issue. @smaranjitghose

**Comment by suraj111999** [comment]
I would like to work on this issue
