### ISSUE TITLE
Remove the location,email id,phone number from the footer of GirlScript Chennai Website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#70]

**Comment by HarshCasper** [comment]
I would like to work on this issue as part of GSSOC'2020. I would be highly obliged if you can grant me permission to work on this issue @smaranjitghose

**Comment by goyalmuskan** [comment]
Please assign me this issue.

**Comment by goyalmuskan** [comment]
@smaranjitghose Do I need to just remove it? Or add something else as well?
