### ISSUE TITLE
Remove program section from GirlScript Chennai website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#71]

**Comment by HarshCasper** [comment]
I would like to work on this issue as part of GSSOC'2020. I would be highly obliged if you can grant me permission to work on this issue @smaranjitghose

**Comment by goyalmuskan** [comment]
Please assign me this issue!

**Comment by shreyakapoor08** [comment]
can i take up this issue?

**Comment by smaranjitghose** [comment]
@HarshCasper @shreyakapoor08 
The website has been shifted to https://github.com/smaranjitghose/girlscript_chennai_website
as a separate project for GSSOC..Please checkout the codebase there and continue contributing there..The issues will be raised shortly there...Meanwhile, You are welcome raise your own issues there
