### ISSUE TITLE
Improve Documentation 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#8]
Currently, README requires some improvements to improve visual inspection of all details for new beginners:(Section wise)
-a description about how flutter works and its widgets
-some details about the different components we have here
-anything else you wish..give a pull request..we will review and confirm

**Comment by smaranjitghose** [comment]
Currently, the  README requires some improvements to improve visual inspection of all details for new beginners.

**Comment by infiniteoverflow** [comment]
i would like to contribute to this. May i know what all should be there?

**Comment by AjinkyaTaranekar** [comment]
Hello sir, I would like to contribute towards this, could you tell what points do I need to mention.

**Comment by VibavariG** [comment]
I would like to contribute to this. Please guide me with what all points I should include

**Comment by annu12340** [comment]
I would also like to work on it

**Comment by minolipvartak** [comment]
I want to work on this issue to document the overview of the app

**Comment by smaranjitghose** [comment]
@minolipvartak  Go forward

**Comment by minolipvartak** [comment]
hello @smaranjitghose I see there is some sort of duplications in the ReadMe doc. 
![image](https://user-images.githubusercontent.com/36539574/77256506-d2740580-6c94-11ea-986f-b4e546b8514b.png)
![image](https://user-images.githubusercontent.com/36539574/77256535-fafbff80-6c94-11ea-80dc-fc98771dfcd2.png)

Can you please reopen this issue and assign it to me for a quick fix?
