### ISSUE TITLE
Improve the Home Page of the GirlScript Chennai Website

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#87]
see the official girlscript foundation for reference

We need to have the following sections:
- Home(The main landing page..summarizing what GirlScript is and its goals)
- Announcements Page
- Team Page
- Contact Us Page
- Achievement Page
- Blog Page

Improve the design of the current one
Please do some research on GirlScript itself and put in the content instead of Lorem Ipsum
At the footer,try to embed a location(using the google maps one)

**Comment by HarshMehta2468** [comment]
@smaranjitghose  I'd like to work on this

**Comment by smaranjitghose** [comment]
For references:
https://srmkzilla.net/
http://dscmanipal.club/

**Comment by manan-bedi2908** [comment]
I would like to work on this issue

**Comment by HarshMehta2468** [comment]
@smaranjitghose I commented first,still the other person was assigned it !!! How come ?

**Comment by smaranjitghose** [comment]
@mySTRiouscoder This is not a First Come First Serve thing. We have to make sure everyone is given an opportunity and all the participants are able to contribute to a same base level...Hence if someone's not assigned anything previously might be given preference..If you wish to contribute on the the same just give a PR and say how you improved..it would surely be considered

**Comment by HarshMehta2468** [comment]
Oh ,Okay !!!  My bad , Sorry for the misunderstanding @smaranjitghose

**Comment by vishakha2108** [comment]
Can I work on this?

**Comment by manan-bedi2908** [comment]
@smaranjitghose now, do @mySTRiouscoder and me have to work together for this?

**Comment by smaranjitghose** [comment]
Yes, i would suggest a collaborative effort since based upon the main page the others will fall in place..or atleast while one of you gives a PR for some X make sure the other gives for Y..knowing that X is done

**Comment by SaranshDawra** [comment]
@smaranjitghose I would like to work on this issue.
