### ISSUE TITLE
Add splash Screen for the application

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/girlscript_app#9]

**Comment by rohg007** [comment]
Hello, can I work on this?

**Comment by smaranjitghose** [comment]
> 
> 
> Hello, can I work on this?

Yes

**Comment by himanshusharma89** [comment]
Hello, I have developed the splash screen, if you like you can assign me this issue

**Comment by smaranjitghose** [comment]
Its already assigned to @rohg007 ... Once he's done..if we need any improvments..you can give a PR for it

**Comment by rohg007** [comment]
What implementation of Splash Screen are we looking for, like a single dart version. Or separate versions for Android and iOS?

**Comment by smaranjitghose** [comment]
Primarily  for android

**Comment by rohg007** [comment]
I've developed one for android, natively so that the white screen that generally appears doesn't appear. I'm working on the iOS one so shall I make a combined PR or 2 separate PRs?

**Comment by smaranjitghose** [comment]
Make separate  2 PRs

**Comment by Anushka-shukla** [comment]
Sir I have made an improved splash screen.

**Comment by smaranjitghose** [comment]
Make a PR..since @rohg007 is assigned  this..first the mentors  will review it and see its free of conflicts  to merge..then yours will be considered for this issue

**Comment by puneethkanna** [comment]
Sir, I had made a splash screen and made a PR, along with other issues.
