### ISSUE TITLE
Social media Logos on contact-us page 

### ISSUE THREAD

**Issue by HarshMehta2468** [smaranjitghose/girlscript_app#95]
The current version has images(.png) as logos  and  not icons which seems kinda not perfect.
Also, updated the links with the official social media handles.

**Comment by HarshMehta2468** [comment]
Issue:
![image](https://user-images.githubusercontent.com/56103228/76118947-5d59cc80-6014-11ea-9af8-7d12461146f1.png)

As evident in the above pic the icons appear quite large

**Comment by nicks101** [comment]
hey @ousnik, can I work on this issue?

**Comment by gpsuhas20** [comment]
please assign me this task.

**Comment by AjinkyaTaranekar** [comment]
Please assign me this issue.
